POC_PI_AWS-web/src/main/java/tn/esprit/jsf_app/presentation/mbeans/ProductCartBean.java
package tn.esprit.jsf_app.presentation.mbeans;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.Part;

import tn.esprit.jsf_app.DTO.*;
import tn.esprit.jsf_app.services.*;

@ManagedBean(name = "productCartBean")
@SessionScoped
public class ProductCartBean implements Serializable {

	int userId = 2;

	@EJB
	ProductCartService productService;

	@PostConstruct
	public void init() {
	}

	List<Product> listAllProduct;

	public List<Product> listOfAllProduct() {
		listAllProduct = productService.GetAllProduct();
		return listAllProduct;
	}

	List<Cart> listAllCart;

	public List<Cart> listOfAllCart() {
		listAllCart = productService.GetAllCartByUserId(1);
		return listAllCart;
	}

	public Cart cartFromView;

	public void setCartFromView(Cart cartFromView) {
		this.cartFromView = cartFromView;
	}

	public void reload() throws IOException {
		ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
		ec.redirect(((HttpServletRequest) ec.getRequest()).getRequestURI());
	}

	public void deleteCart() throws IOException {
		productService.DeleteCart(cartFromView.getId());
		reload();
	}

	String prix1, prix2, keyword;
	private int id;
	private String nom;
	private int prix;
	private  String imageString;
	private String category;
	private Byte[] imageByte;
	private int quantite;
	public String description;
	private static String img1;
	

	public static String getImg1() {
		return img1;
	}

	public static void setImg1(String img1) {
		ProductCartBean.img1 = img1;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getPrix() {
		return prix;
	}

	public void setPrix(int prix) {
		this.prix = prix;
	}

	public  String getImageString() {
		return imageString;
	}

	public  void setImageString(String imageString) {
		this.imageString = imageString;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Byte[] getImageByte() {
		return imageByte;
	}

	public void setImageByte(Byte[] imageByte) {
		this.imageByte = imageByte;
	}

	public int getQuantite() {
		return quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	public String getPrix1() {
		return prix1;
	}

	public void setPrix1(String prix1) {
		this.prix1 = prix1;
	}

	public String getPrix2() {
		return prix2;
	}

	public void setPrix2(String prix2) {
		this.prix2 = prix2;
	}

	public String getKeyword() {
		return keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	List<Cart> listAllCartByUserId;

	public List<Cart> Search() throws ParseException {

		if (((null == prix1 || "".equals(prix1)) && (null == prix2 || "".equals(prix2)))
				&& (null == keyword || "".equals(keyword))) {
			listAllCartByUserId = productService.GetAllCartByUserId(1);
			return listAllCartByUserId;
		} else if (null == keyword || "".equals(keyword)) {
			listAllCartByUserId = productService.SearchByPrice(prix1, prix2, productService.GetAllCartByUserId(1));
			return listAllCartByUserId;

		} else if ((null == prix1 || "".equals(prix1)) || (null == prix2 || "".equals(prix2))) {
			listAllCartByUserId = productService.searchProductByName(keyword, productService.GetAllCartByUserId(1));
			return listAllCartByUserId;
		} else {
			listAllCartByUserId = productService.searchProductByName(keyword,
					productService.SearchByPrice(prix1, prix2, productService.GetAllCartByUserId(1)));
			return listAllCartByUserId;
		}
	}

	public List<Cart> getSearch() throws ParseException {
		return listAllCartByUserId;
	}

	public String DisplayMyCartHistory() throws ParseException {
		Search();
		String navigateTo = "/Consomi-web/template/ProductCart/HistoryPurchase.jsf";
		return navigateTo;
	}

	public boolean TestImage(Product p) {
		if (p.imageString.length() > 20)
			return true;
		return false;
	}
	public boolean TestImage1(String image) {
		if (image.length() > 20)
			return true;
		return false;
	}

	

	private Part logo;

	public Part getLogo() {
		return logo;
	}

	public void setLogo(Part logo) {
		this.logo = logo;
	}

	public void doUpload() {

		try {
			InputStream in = logo.getInputStream();
			img1 = logo.getSubmittedFileName();
			File f = new File(
					"C:\\Users\\Hsine\\Desktop\\souhaib\\PiDevJee-master\\POC_PI_AWS-web\\src\\main\\webapp\\Ressources\\Uploads\\"
							+ logo.getSubmittedFileName());
			System.out.println("hsiiiiiine" + f.getAbsolutePath());
			f.createNewFile();
			FileOutputStream out = new FileOutputStream(f);

			byte[] buffer = new byte[1024];
			int length;

			while ((length = in.read(buffer)) > 0) {
				out.write(buffer, 0, length);
			}

			out.close();
			in.close();

		} catch (Exception e) {
			e.printStackTrace(System.out);
		}

	}

	public String addProduct() throws ParseException {
		System.out.println("hhhhhhh" + imageString);
		productService.Create(new Product(nom, prix, img1, category, quantite, description));

		this.setNom(null);
		this.setPrix(0);
		this.setCategory(null);
		this.setQuantite(0);
		this.setDescription(null);
		this.getSearch();

		return "/ProductCart/Index?faces-redirect=true";

	}

	private String img;

	public String getImg() {
		return img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public String Details(Product p)  {
		System.out.println("hhhhhhh11" + p.imageString);
		this.setId(p.getId());
		this.setNom(p.getNom());
		this.setPrix(p.getPrix());
		this.setCategory(p.getCategory());
		this.setQuantite(p.getQuantite());
		this.setDescription(p.getDescription());
		this.setImageString( p.imageString);

		return "/ProductCart/DisplaySelectedProduct?faces-redirect=true";

	}

	public String AddToCart() {
productService.AddProductToMyCart(id, new Product(id,quantite));
		return "/ProductCart/Index?faces-redirect=true";
	}
	private List<CartLine> Cartlines= new ArrayList<CartLine>();
	public List<CartLine> getCartlines() {
		Cartlines=productService.MyCart();
		
		return Cartlines;
	}
	public String Confirm() {
		System.out.println("hhhhhh");
		productService.ConfirmPurchase();
		return "/ProductCart/HistoryPurchase?faces-redirect=true";

	}
	public String Remove(CartLine c) {
		productService.DeleteCart(c.cartId);
		return "/ProductCart/MyCart?faces-redirect=true";
	}
	public String UpdateQuan(CartLine c) {
		this.setId(c.getId());
		this.setNom(c.getNomProd());
		this.setPrix(c.getPrixunitaire());
		this.setCategory(c.getMyProduct().getCategory());
		this.setQuantite(c.getQuantiteChoisie());
		this.setDescription(c.getMyProduct().getDescription());
		this.imageString = c.getMyProduct().getImageString();
		return "/ProductCart/EditCartLine?faces-redirect=true";
	}
	public String PutCartLine() throws InterruptedException {

		productService.Update(getId(),
				new CartLine(getId(),getQuantite()));
		this.setId(0);
		this.setQuantite(0);
		

		return "/ProductCart/MyCart?faces-redirect=true";
	}

}

POC_PI_AWS-web/src/main/webapp/ProductCart/Create.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/Template/Template.xhtml" xmlns:p="http://primefaces.org/ui">

	<ui:param name="page_name" value="Create" />

	<ui:define name="body">
		<head>
<style>
.image-upload1>input {
	display: none;
}

img {
	width: 180px;
	height: 180px;
	border-radius: 20px;
}

input[type=file] {
	padding: 10px;
	background: #2d2d2d;
}
</style>

		</head>




		<h:form enctype="multipart/form-data">

			<div class="form-horizontal">
				<div class="container">
					<br />
					<div class="col-md-offset-5 col-md-10">
						<h4>Add Your Product</h4>
						.
					</div>


					<div class="form-group">
						Name
						<div class="col-md-8">
							<h:inputText value="#{productCartBean.nom}" pt:placeholder="Name"
								styleClass="form-control" id="name" required="true"
								requiredMessage="required" />
						</div>
						<h:message for="name"></h:message>

					</div>

					<div class="form-group">
						Category
						<div class="col-md-8">
							<h:inputText value="#{productCartBean.category}"
								pt:placeholder="Category" styleClass="form-control"
								id="category" required="true" requiredMessage="required" />
						</div>
						<h:message for="category"></h:message>
					</div>

					<div class="form-group">
						Price
						<div class="col-md-8">
							<h:inputText value="#{productCartBean.prix}"
								pt:placeholder="Price" styleClass="form-control" id="prix"
								required="true" requiredMessage="required" />
						</div>
						<h:message for="prix"></h:message>
					</div>

					<div class="form-group">
						Quantity
						<div class="col-md-8">
							<h:inputText value="#{productCartBean.quantite}"
								pt:placeholder="Name" styleClass="form-control" id="quantite"
								required="true" requiredMessage="required" />
						</div>
						<h:message for="quantite"></h:message>
					</div>
					<div class="form-group">
						Description
						<div class="col-md-8">
							<h:inputText value="#{productCartBean.description}"
								pt:placeholder="Description" styleClass="form-control"
								id="description" required="true" requiredMessage="required" />
						</div>
						<h:message for="description"></h:message>
					</div>


					<div class="form-group">
						<div class="col-md-offset-5 col-md-10">
							<div class="image-upload1">
								<div id="upload-button">
									<h:inputFile value="#{productCartBean.logo}">

										<f:passThroughAttribute name="accept" value="image/png" />
										<f:ajax listener="#{productCartBean.doUpload()}"
											render="@form" />


									</h:inputFile>
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="col-md-offset-2 col-md-10">
								<h:commandButton action="#{productCartBean.addProduct}"
									value="Create Product" styleClass="btn btn-primary pull-center"
									id="hsine" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</h:form>
	</ui:define>
</ui:composition>

POC_PI_AWS-web/src/main/webapp/ProductCart/DisplaySelectedProduct.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/Template/Template.xhtml" xmlns:p="http://primefaces.org/ui">

	<ui:param name="page_name" value="Details" />

	<ui:define name="body">

		<h4>Product</h4>
		<h:form>

			<div class="row">
				<div class="col-lg-6">

					<div class="product-pic-zoom">
						<c:if test="#{ productCartBean.TestImage1(productCartBean.imageString)}">
							<h:commandButton
								image="data:image/jpg;base64,#{productCartBean.imageString} "
								styleClass="button" value="add to cart">
							</h:commandButton>
						</c:if>
						<c:if
							test="#{not productCartBean.TestImage1(productCartBean.imageString)}">
							<h:graphicImage
								value="../Ressources/Uploads/#{productCartBean.imageString}" />

						</c:if>

						<div class="zoom-icon">
							<i class="fa fa-search-plus"></i>
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="product-details">
						<div class="pd-title">
							<span>oranges</span>
							<h3>
								<h:outputText value="#{productCartBean.nom}" />
							</h3>
							<a href="#" class="heart-icon"><i class="icon_heart_alt"></i></a>
						</div>
						<div class="pd-rating">
							<i class="fa fa-star"></i> <i class="fa fa-star"></i> <i
								class="fa fa-star"></i> <i class="fa fa-star"></i> <i
								class="fa fa-star-o"></i> <span>(5)</span>
						</div>
						<div class="pd-desc">
							<p>
								<h:outputText value="#{productCartBean.description}" />
							</p>
							<h4>
								<h:outputText value="#{productCartBean.prix}" />
							</h4>
						</div>


						<h:inputText value="#{productCartBean.quantite}"
							pt:placeholder="Quantity" styleClass="form-control" id="quantity"
							required="true" requiredMessage="required" />
						<h:message for="quantity"></h:message>
						<h:commandButton action="#{productCartBean.AddToCart}"
							value="Add to my cart" styleClass="btn btn-primary pull-center"
							id="hsine" />
					</div>
					<ul class="pd-tags">
						<li><span>CATEGORY</span>: <h:outputText
								value="#{productCartBean.category}" /></li>
					</ul>

				</div>
			</div>

		</h:form>

	</ui:define>
</ui:composition>

POC_PI_AWS-web/src/main/webapp/ProductCart/EditCartLine.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/Template/Template.xhtml" xmlns:p="http://primefaces.org/ui">

	<ui:param name="page_name" value="Edit CartLine" />

	<ui:define name="body">

		<h4>Product</h4>
		<h:form>

			<div class="row">
				<div class="col-lg-6">

					<div class="product-pic-zoom">
						<c:if
							test="#{ productCartBean.TestImage1(productCartBean.imageString)}">

							<h:commandButton
								image="data:image/jpg;base64,#{productCartBean.imageString} "
								styleClass="button" value="add to cart">
							</h:commandButton>
							</c:if>
							<c:if
							test="#{ not productCartBean.TestImage1(productCartBean.imageString)}">

							<h:graphicImage
								value="../Ressources/Uploads/#{productCartBean.imageString}" />
							</c:if>
							<div class="zoom-icon">
								<i class="fa fa-search-plus"></i>
							</div>
							
					</div>
				</div>
				<div class="col-lg-6">
					<div class="product-details">
						<div class="pd-title">
							<span>oranges</span>
							<h3>
								<h:outputText value="#{productCartBean.nom}" />
							</h3>
							<a href="#" class="heart-icon"><i class="icon_heart_alt"></i></a>
						</div>
						<div class="pd-rating">
							<i class="fa fa-star"></i> <i class="fa fa-star"></i> <i
								class="fa fa-star"></i> <i class="fa fa-star"></i> <i
								class="fa fa-star-o"></i> <span>(5)</span>
						</div>
						<div class="pd-desc">
							<p>
								<h:outputText value="#{productCartBean.description}" />
							</p>
							<h4>
								<h:outputText value="#{productCartBean.prix}" />
							</h4>
						</div>


						<h:inputText value="#{productCartBean.quantite}"
							pt:placeholder="Quantity" styleClass="form-control" id="quantity"
							required="true" requiredMessage="required" />
						<h:message for="quantity"></h:message>
						<h:commandButton action="#{productCartBean.PutCartLine}"
							value="Update Quantity" styleClass="btn btn-primary pull-center"
							id="hsine" />
					</div>
					<ul class="pd-tags">
						<li><span>CATEGORY</span>: <h:outputText
								value="#{productCartBean.category}" /></li>
					</ul>

				</div>
			</div>

		</h:form>

	</ui:define>
</ui:composition>

POC_PI_AWS-web/src/main/webapp/ProductCart/HistoryPurchase.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/Template/Template.xhtml" xmlns:p="http://primefaces.org/ui">

	<ui:param name="page_name" value="History Purchase" />

	<ui:define name="body">

		<h2>Cart History</h2>

		<div class="login-form-grids animated wow slideInUp"
			data-wow-delay=".5s">
			<h:form>
				<h:inputText pt:placeholder="product name"
					value="#{productCartBean.keyword}"></h:inputText>
				<div class="row">
					<div class="col-lg-6">
						<h:inputText value="#{productCartBean.prix1}"
							pt:placeholder="minimum price">
						</h:inputText>
					</div>
					<div class="col-lg-6">
						<h:inputText value="#{productCartBean.prix2}"
							pt:placeholder="maximum price">

						</h:inputText>

					</div>
				</div>



				<h:commandButton class="btn btn-default btn-purple" value="Search"
					action="#{productCartBean.Search()}"></h:commandButton>
			</h:form>
		</div>
		<br />
		<c:forEach var="cart" items="#{productCartBean.getSearch()}"
			varStatus="status">
			<h3>
				you have confirmed payment for this Cart on <span
					style="color: #3399CC"> <h:outputText
						style="font-weight:bold" value="#{cart.dateAchat}">
						<f:convertDateTime locale="en" timeStyle="short" type="both"
							dateStyle="full" />
					</h:outputText>

				</span> which contains the products below and you paid <span
					style="color: #3399CC"><h:outputText
						style="font-weight:bold" value="#{cart.prixTotal}" /> € </span>
			</h3>

			<section class="shopping-cart spad">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<div class="cart-table">
								<table>
									<thead>
										<tr>
											<th>Image</th>
											<th class="p-name">Product Name</th>
											<th>Price</th>
											<th>Quantity</th>
											<th>Total</th>


										</tr>
									</thead>
									<tbody>
										<c:forEach var="cartline" items="#{cart.cartLines}"
											varStatus="status">
											<tr>
											<c:if test="#{ productCartBean.TestImage(cartline.myProduct)}">

												<td class="cart-pic first-row"><img class="center"
													widht="170" height="170"
													src="data:image/jpg;base64,#{cartline.myProduct.imageString}" /></td>
												</c:if>	
												<c:if test="#{not productCartBean.TestImage(cartline.myProduct)}">

												<td class="cart-pic first-row"><h:graphicImage
														value="../Ressources/Uploads/#{cartline.myProduct.imageString}" /></td>
												</c:if>	
												<td class="cart-title first-row">
													<h5>
														<h:outputText value="#{cartline.myProduct.nom}" />
													</h5>
												</td>
												<td class="p-price first-row"><h:outputText
														value="#{cartline.myProduct.prix}" />$</td>
												<td class="qua-col first-row">
													<div class="quantity">
														<h:outputText value="#{cartline.quantiteChoisie}" />
													</div>
												</td>
												<td class="total-price first-row"><h:outputText
														value="#{cartline.prixTotal}" />$</td>

											</tr>
											</c:forEach>
									</tbody>
								</table>
								                            <div align="right">Total= #{cart.prixTotal} € </div>
								
							</div>

						</div>
					</div>
				</div>
			</section>
		</c:forEach>

	</ui:define>
</ui:composition>

POC_PI_AWS-web/src/main/webapp/ProductCart/Index.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/Template/Template.xhtml" xmlns:p="http://primefaces.org/ui">

	<ui:param name="page_name" value="Index" />

	<ui:define name="body">
		<div class="row">

			<c:forEach var="productList"
				items="#{productCartBean.listOfAllProduct()}" varStatus="status">
				<div class="col-lg-3 col-sm-6">
					<div class="product-item">
						<div class="pi-pic">
							<h:form>
								<c:if test="#{not productCartBean.TestImage(productList)}">
									<h:graphicImage
										value="../Ressources/Uploads/#{productList.imageString}" />
								</c:if>
								<c:if test="#{ productCartBean.TestImage(productList)}">
									<h:commandButton
										image="data:image/jpg;base64,#{productList.imageString} "
										styleClass="button" value="add to cart">
									</h:commandButton>
								</c:if>

								<div class="icon">
									<i class="icon_heart_alt"></i>
								</div>
								<ul>
									<li class="quick-view"><h:commandLink
											action="#{productCartBean.Details(productList)}">+ Quick View</h:commandLink></li>
								</ul>
							</h:form>

						</div>
						<div class="pi-text">
							<div class="catagory-name">
								<h:outputText value="#{productList.category}" />
							</div>
							<a href="#">
								<h5>
									<h:outputText value="#{productList.nom}" />
								</h5>
							</a>
							<div class="product-price">
								<h:outputText value="#{productList.prix}" />
								$
							</div>
						</div>
					</div>
				</div>

			</c:forEach>
		</div>
	</ui:define>
</ui:composition>

POC_PI_AWS-web/src/main/webapp/ProductCart/MyCart.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	template="/Template/Template.xhtml" xmlns:p="http://primefaces.org/ui">

	<ui:param name="page_name" value="My Cart" />

	<ui:define name="body">
		<section class="shopping-cart spad">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="cart-table">
							<table>
								<thead>
									<tr>
										<th>Image</th>
										<th class="p-name">Product Name</th>
										<th>Price</th>
										<th>Quantity</th>
										<th>Total</th>
										<th><i class="ti-close"></i></th>
										<th>Update Quantity</th>

									</tr>
								</thead>
								<tbody>
									<c:forEach var="c" items="#{productCartBean.cartlines}"
										varStatus="status">
										<tr>
											<c:if test="#{not productCartBean.TestImage(c.myProduct)}">
												<td class="cart-pic first-row"><h:graphicImage
														value="../Ressources/Uploads/#{c.myProduct.imageString}" />
												</td>
											</c:if>
											<c:if test="#{ productCartBean.TestImage(c.myProduct)}">
												<td class="cart-pic first-row"><h:commandButton
														image="data:image/jpg;base64,#{c.myProduct.imageString}"
														styleClass="button" value="add to cart">
													</h:commandButton></td>

											</c:if>
											<td class="cart-title first-row">
												<h5>
													<h:outputText value="#{c.nomProd}" />
												</h5>
											</td>
											<td class="p-price first-row"><h:outputText
													value="#{c.prixunitaire}" /> $</td>
											<td class="qua-col first-row">
												<div class="quantity">
													<h:outputText value="#{c.quantiteChoisie}" />
												</div>
											</td>
											<td class="total-price first-row"><h:outputText
													value="#{c.prixTotal}" />$</td>
											<td class="close-td first-row"><h:form>
													<h:commandLink action="#{productCartBean.Remove(c)}">
														<i class="ti-close"> </i>
													</h:commandLink>
												</h:form></td>
											<td class="close-td first-row"><h:form>
													<h:commandLink action="#{productCartBean.UpdateQuan(c)}">
														<i class="ti-apple"> </i>
													</h:commandLink>
												</h:form></td>

										</tr>
									</c:forEach>


								</tbody>
							</table>
						</div>
						<div class="row">
							<div class="col-lg-4">
								<div class="cart-buttons">
									<a href="/POC_PI_AWS-web/ProductCart/Index.jsf"
										class="primary-btn continue-shop">Continue shopping</a>
								</div>

							</div>
							<div class="col-lg-4 offset-lg-4">
								<div class="proceed-checkout">
									<h:form>

										<h:commandLink action="#{productCartBean.Confirm}"
											value="Confirm
										Purchase" styleClass="proceed-btn" />
									</h:form>

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	</ui:define>
</ui:composition>